arch: 
  - amd64
  - ppc64le
language: c
os: linux
dist: xenial
before_script:
  - | 
   if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
     sudo apt-get install libevent-dev
   fi
script:
  - ./autogen.sh
  - ./configure
  - make
  - make test
  - make install
